# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "virtio_pci" "usbhid" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f0ee58a6-edb8-4f1d-b594-ba54c9282cb2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6DA4-B025";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2e8a49eb-9a86-4834-8a0a-e10955b4e0a7"; }
    ];

  # Samba Shares
  fileSystems."/home/querzion/Shares/Gaming" = {
    device = "//192.168.0.3/archive.gaming";
    fsType = "cifs";
    options = [
      "credentials=/home/querzion/Shares/samba.cred"
      "uid=1000"
      "gid=1000"
      "rw"
    ];
  };

  fileSystems."/home/querzion/Shares/Data" = {
    device = "//192.168.0.3/archive.data";
    fsType = "cifs";
    options = [
      "credentials=/home/querzion/Shares/samba.cred"
      "uid=1000"
      "gid=1000"
      "rw"
    ];
  };

  fileSystems."/home/querzion/Shares/OBS-Studio" = {
    device = "//192.168.0.3/archive.obs-studio";
    fsType = "cifs";
    options = [
      "credentials=/home/querzion/Shares/samba.cred"
      "uid=1000"
      "gid=1000"
      "rw"
    ];
  };

  fileSystems."/home/querzion/Shares/Other" = {
    device = "//192.168.0.3/archive.other";
    fsType = "cifs";
    options = [
      "credentials=/home/querzion/Shares/samba.cred"
      "uid=1000"
      "gid=1000"
      "rw"
    ];
  };

  fileSystems."/home/querzion/Shares/Work" = {
    device = "//192.168.0.3/archive.work";
    fsType = "cifs";
    options = [
      "credentials=/home/querzion/Shares/samba.cred"
      "uid=1000"
      "gid=1000"
      "rw"
    ];
  };

  fileSystems."/home/querzion/Shares/Querzion" = {
    device = "//192.168.0.3/user.querzion";
    fsType = "cifs";
    options = [
      "credentials=/home/querzion/Shares/samba.cred"
      "uid=1000"
      "gid=1000"
      "rw"
    ];
  };



  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
